// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.6
// source: proto/micelio.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope wraps every message on the wire.
// msg_type is numeric for extensibility: core 1-99, plugin 1000+.
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`          // UUID v4, unique per message
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`             // node_id of originator
	LamportTs     uint64                 `protobuf:"varint,3,opt,name=lamport_ts,json=lamportTs,proto3" json:"lamport_ts,omitempty"`         // Lamport clock (reserved, unused in Phase 2)
	HopCount      uint32                 `protobuf:"varint,4,opt,name=hop_count,json=hopCount,proto3" json:"hop_count,omitempty"`            // decremented at each hop
	MsgType       uint32                 `protobuf:"varint,5,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`               // payload type
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`                               // serialized inner message
	Signature     []byte                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`                           // ED25519 signature (excludes hop_count and sender_pubkey)
	SenderPubkey  []byte                 `protobuf:"bytes,8,opt,name=sender_pubkey,json=senderPubkey,proto3" json:"sender_pubkey,omitempty"` // raw 32-byte ED25519 public key of originator
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_micelio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micelio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_micelio_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Envelope) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Envelope) GetLamportTs() uint64 {
	if x != nil {
		return x.LamportTs
	}
	return 0
}

func (x *Envelope) GetHopCount() uint32 {
	if x != nil {
		return x.HopCount
	}
	return 0
}

func (x *Envelope) GetMsgType() uint32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Envelope) GetSenderPubkey() []byte {
	if x != nil {
		return x.SenderPubkey
	}
	return nil
}

// PeerHello is sent by the initiator after the Noise handshake.
type PeerHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Reachable     bool                   `protobuf:"varint,4,opt,name=reachable,proto3" json:"reachable,omitempty"`
	ListenAddr    string                 `protobuf:"bytes,5,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	Ed25519Pubkey []byte                 `protobuf:"bytes,6,opt,name=ed25519_pubkey,json=ed25519Pubkey,proto3" json:"ed25519_pubkey,omitempty"` // raw 32-byte ED25519 public key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerHello) Reset() {
	*x = PeerHello{}
	mi := &file_proto_micelio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerHello) ProtoMessage() {}

func (x *PeerHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micelio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerHello.ProtoReflect.Descriptor instead.
func (*PeerHello) Descriptor() ([]byte, []int) {
	return file_proto_micelio_proto_rawDescGZIP(), []int{1}
}

func (x *PeerHello) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PeerHello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PeerHello) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PeerHello) GetReachable() bool {
	if x != nil {
		return x.Reachable
	}
	return false
}

func (x *PeerHello) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

func (x *PeerHello) GetEd25519Pubkey() []byte {
	if x != nil {
		return x.Ed25519Pubkey
	}
	return nil
}

// PeerHelloAck is the responder's reply to PeerHello.
// Wire format is identical to PeerHello; msg_type=2 distinguishes it.
// Implementations MUST serialize/deserialize as PeerHello on the wire.
type PeerHelloAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Reachable     bool                   `protobuf:"varint,4,opt,name=reachable,proto3" json:"reachable,omitempty"`
	ListenAddr    string                 `protobuf:"bytes,5,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	Ed25519Pubkey []byte                 `protobuf:"bytes,6,opt,name=ed25519_pubkey,json=ed25519Pubkey,proto3" json:"ed25519_pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerHelloAck) Reset() {
	*x = PeerHelloAck{}
	mi := &file_proto_micelio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerHelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerHelloAck) ProtoMessage() {}

func (x *PeerHelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micelio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerHelloAck.ProtoReflect.Descriptor instead.
func (*PeerHelloAck) Descriptor() ([]byte, []int) {
	return file_proto_micelio_proto_rawDescGZIP(), []int{2}
}

func (x *PeerHelloAck) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PeerHelloAck) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PeerHelloAck) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PeerHelloAck) GetReachable() bool {
	if x != nil {
		return x.Reachable
	}
	return false
}

func (x *PeerHelloAck) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

func (x *PeerHelloAck) GetEd25519Pubkey() []byte {
	if x != nil {
		return x.Ed25519Pubkey
	}
	return nil
}

// ChatMessage is a partyline chat message.
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nick          string                 `protobuf:"bytes,1,opt,name=nick,proto3" json:"nick,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_micelio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micelio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_micelio_proto_rawDescGZIP(), []int{3}
}

func (x *ChatMessage) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *ChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// PeerInfo describes a known peer for exchange.
type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Reachable     bool                   `protobuf:"varint,3,opt,name=reachable,proto3" json:"reachable,omitempty"`
	Ed25519Pubkey []byte                 `protobuf:"bytes,4,opt,name=ed25519_pubkey,json=ed25519Pubkey,proto3" json:"ed25519_pubkey,omitempty"`
	LastSeen      uint64                 `protobuf:"varint,5,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_proto_micelio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micelio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_proto_micelio_proto_rawDescGZIP(), []int{4}
}

func (x *PeerInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PeerInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *PeerInfo) GetReachable() bool {
	if x != nil {
		return x.Reachable
	}
	return false
}

func (x *PeerInfo) GetEd25519Pubkey() []byte {
	if x != nil {
		return x.Ed25519Pubkey
	}
	return nil
}

func (x *PeerInfo) GetLastSeen() uint64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

// PeerExchange carries a list of known peers (msg_type=4).
type PeerExchange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerExchange) Reset() {
	*x = PeerExchange{}
	mi := &file_proto_micelio_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerExchange) ProtoMessage() {}

func (x *PeerExchange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micelio_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerExchange.ProtoReflect.Descriptor instead.
func (*PeerExchange) Descriptor() ([]byte, []int) {
	return file_proto_micelio_proto_rawDescGZIP(), []int{5}
}

func (x *PeerExchange) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

var File_proto_micelio_proto protoreflect.FileDescriptor

const file_proto_micelio_proto_rawDesc = "" +
	"\n" +
	"\x13proto/micelio.proto\x12\amicelio\"\xfa\x01\n" +
	"\bEnvelope\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x1d\n" +
	"\n" +
	"lamport_ts\x18\x03 \x01(\x04R\tlamportTs\x12\x1b\n" +
	"\thop_count\x18\x04 \x01(\rR\bhopCount\x12\x19\n" +
	"\bmsg_type\x18\x05 \x01(\rR\amsgType\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\x12#\n" +
	"\rsender_pubkey\x18\b \x01(\fR\fsenderPubkey\"\xb8\x01\n" +
	"\tPeerHello\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x1c\n" +
	"\treachable\x18\x04 \x01(\bR\treachable\x12\x1f\n" +
	"\vlisten_addr\x18\x05 \x01(\tR\n" +
	"listenAddr\x12%\n" +
	"\x0eed25519_pubkey\x18\x06 \x01(\fR\red25519Pubkey\"\xbb\x01\n" +
	"\fPeerHelloAck\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x1c\n" +
	"\treachable\x18\x04 \x01(\bR\treachable\x12\x1f\n" +
	"\vlisten_addr\x18\x05 \x01(\tR\n" +
	"listenAddr\x12%\n" +
	"\x0eed25519_pubkey\x18\x06 \x01(\fR\red25519Pubkey\"S\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04nick\x18\x01 \x01(\tR\x04nick\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\"\x99\x01\n" +
	"\bPeerInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x1c\n" +
	"\treachable\x18\x03 \x01(\bR\treachable\x12%\n" +
	"\x0eed25519_pubkey\x18\x04 \x01(\fR\red25519Pubkey\x12\x1b\n" +
	"\tlast_seen\x18\x05 \x01(\x04R\blastSeen\"7\n" +
	"\fPeerExchange\x12'\n" +
	"\x05peers\x18\x01 \x03(\v2\x11.micelio.PeerInfoR\x05peersB\x13Z\x11micelio/pkg/protob\x06proto3"

var (
	file_proto_micelio_proto_rawDescOnce sync.Once
	file_proto_micelio_proto_rawDescData []byte
)

func file_proto_micelio_proto_rawDescGZIP() []byte {
	file_proto_micelio_proto_rawDescOnce.Do(func() {
		file_proto_micelio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_micelio_proto_rawDesc), len(file_proto_micelio_proto_rawDesc)))
	})
	return file_proto_micelio_proto_rawDescData
}

var file_proto_micelio_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_micelio_proto_goTypes = []any{
	(*Envelope)(nil),     // 0: micelio.Envelope
	(*PeerHello)(nil),    // 1: micelio.PeerHello
	(*PeerHelloAck)(nil), // 2: micelio.PeerHelloAck
	(*ChatMessage)(nil),  // 3: micelio.ChatMessage
	(*PeerInfo)(nil),     // 4: micelio.PeerInfo
	(*PeerExchange)(nil), // 5: micelio.PeerExchange
}
var file_proto_micelio_proto_depIdxs = []int32{
	4, // 0: micelio.PeerExchange.peers:type_name -> micelio.PeerInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_micelio_proto_init() }
func file_proto_micelio_proto_init() {
	if File_proto_micelio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_micelio_proto_rawDesc), len(file_proto_micelio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_micelio_proto_goTypes,
		DependencyIndexes: file_proto_micelio_proto_depIdxs,
		MessageInfos:      file_proto_micelio_proto_msgTypes,
	}.Build()
	File_proto_micelio_proto = out.File
	file_proto_micelio_proto_goTypes = nil
	file_proto_micelio_proto_depIdxs = nil
}
